- op: add
  path: /rules/0
  value:
    apiGroups:
    - bosh.akgupta.ca
    resources:
    - directors
    verbs:
    - get
    - list
    - watch
- op: add
  path: /rules/0
  value:
    apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
    - list
    - create
    - delete
    - watch