
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - bosh.akgupta.ca
  resources:
  - releases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - bosh.akgupta.ca
  resources:
  - releases/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - bosh.akgupta.ca
  resources:
  - stemcells
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - bosh.akgupta.ca
  resources:
  - stemcells/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - bosh.akgupta.ca
  resources:
  - teams
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - bosh.akgupta.ca
  resources:
  - teams/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - bosh.akgupta.ca
  resources:
  - vmextensions
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - bosh.akgupta.ca
  resources:
  - vmextensions/status
  verbs:
  - get
  - update
  - patch
