apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: networks.bosh.akgupta.ca
spec:
  additionalPrinterColumns:
    - name: Type
      type: string
      description: The type of the BOSH Network
      JSONPath: .status.original_spec.type
      priority: 0
    - name: Available
      type: boolean
      description: Indicates this BOSH Network is available for use
      JSONPath: .status.available
      priority: 0
    - name: Warning
      type: string
      description: Warning to display if custom resource has been mutated
      JSONPath: .status.warning
      priority: 0
    - name: User-provided Type
      type: string
      description: Same as 'Type' unless resource has been mutated
      JSONPath: .spec.type
      priority: 1