apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: deployments.bosh.akgupta.ca
spec:
  additionalPrinterColumns:
    - name: Replicas
      type: integer
      description: Number of replicas
      JSONPath: .spec.replicas
      priority: 0
    - name: Available
      type: boolean
      description: Indicates this BOSH Deployment is available for use
      JSONPath: .status.available
      priority: 0
    - name: Network
      type: string
      description: Network for the Deployment
      JSONPath: .spec.network
      priority: 0
    - name: Base Image
      type: string
      description: Base Image for the Deployment
      JSONPath: .spec.base_image
      priority: 0