apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: releases.bosh.akgupta.ca
spec:
  additionalPrinterColumns:
    - name: Release Name
      type: string
      description: The name of the BOSH release
      JSONPath: .status.originalSpec.releaseName
      priority: 0
    - name: Version
      type: string
      description: The version of the BOSH release
      JSONPath: .status.originalSpec.version
      priority: 0
    - name: Available
      type: boolean
      description: Indicates this BOSH release is available for use
      JSONPath: .status.available
      priority: 0
    - name: Warning
      type: string
      description: Warning to display if custom resource has been mutated
      JSONPath: .status.warning
      priority: 0
    - name: URL
      type: string
      description: The URL from which the Director fetches the BOSH release
      JSONPath: .status.originalSpec.url
      priority: 1
    - name: SHA1
      type: string
      description: The SHA1 that should match the artifact fetched from the URL
      JSONPath: .status.originalSpec.sha1
      priority: 1
    - name: User-provided Release Name
      type: string
      description: Same as 'Release Name' unless resource has been mutated 
      JSONPath: .spec.releaseName
      priority: 1
    - name: User-provided Version
      type: string
      description: Same as 'Version' unless resource has been mutated 
      JSONPath: .spec.version
      priority: 1
    - name: User-provided URL
      type: string
      description: Same as 'URL' unless resource has been mutated 
      JSONPath: .spec.url
      priority: 1
    - name: User-provided SHA1
      type: string
      description: Same as 'SHA1' unless resource has been mutated 
      JSONPath: .spec.sha1
      priority: 1
