apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: directors.bosh.akgupta.ca
spec:
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            url:
              minLength: 1
            ca_cert:
              minLength: 1
            uaa_url:
              minLength: 1
            uaa_ca_cert:
              minLength: 1
            uaa_client:
              minLength: 1
            uaa_client_secret:
              minLength: 1
