apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: deployments.bosh.akgupta.ca
spec:
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            azs:
              type: array
              minItems: 1
              items:
                type: string
                minLength: 1
            replicas:
              type: integer
            containers:
              type: array
              minItems: 1
              items:
                type: object
                properties:
                  role:
                    type: string
                    minLength: 1
                  resources:
                    type: object
                    properties:
                      ram:
                        type: integer
                        minimum: 1
                      cpu:
                        type: integer
                        minimum: 1
                      ephemeral_disk_size:
                        type: integer
                        minimum: 1
                      persistent_disk_size:
                        type: integer
                        minimum: 1
            extensions:
              type: array
              items:
                type: string
                minLength: 1
            base_iamge:
              type: string
              minLength: 1
            network:
              type: string
              minLength: 1
            update_strategy:
              type: object
              properties:
                min_ready_seconds:
                  type: integer
                max_ready_seconds:
                  type: integer
                max_unavailable_percent:
                  type: string
                max_unavailable_replicas:
                  type: integer
                type:
                  type: string
                  enum: ["delete-create", "create-swap-delete"]