apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: stemcells.bosh.akgupta.ca
spec:
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            stemcellName:
              minLength: 1
            version:
              minLength: 1
            url:
              minLength: 1
            sha1:
              minLength: 1
