apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: compilations.bosh.akgupta.ca
spec:
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            replicas:
              type: integer
              minimum: 1
            cpu:
              type: integer
              minimum: 1
            ram:
              type: integer
              minimum: 1
            ephemeral_disk_size:
              type: integer
              minimum: 1
            network_type:
              type: string
              enum: ["manual", "dynamic"]
            subnet_range:
              type: string
              pattern: '^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\/(?:[0-9]|[1-2][0-9]|3[0-2])$'
            subnet_gateway:
              type: string
              pattern: '^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
            subnet_dns:
              type: array
              minItems: 1
              items:
                type: string
                pattern: '^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
            subnet_reserved:
              type: array
              items:
                type: string
            director:
              type: string
              minLength: 1
