apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: teams.bosh.akgupta.ca
spec:
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            director:
              minLength: 1