apiVersion: apps/v1
kind: Deployment
metadata:
  name: boshv3-controller-manager
  namespace: <BOSH_SYSTEM_NAMESPACE>
spec:
  template:
    spec:
      containers:
      # Change the value of image field below to your controller image URL
      - image: amitkgupta/boshv3-controller:latest
        name: manager
