# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/bosh.akgupta.ca_releases.yaml
- bases/bosh.akgupta.ca_stemcells.yaml
- bases/bosh.akgupta.ca_directors.yaml
- bases/bosh.akgupta.ca_teams.yaml
- bases/bosh.akgupta.ca_vmextensions.yaml
- bases/bosh.akgupta.ca_azs.yaml
- bases/bosh.akgupta.ca_networks.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
- patches/categories_in_releases.yaml
- patches/nonempty_spec_properties_validations_in_releases.yaml
- patches/additional_printer_columns_in_releases.yaml
- patches/status_subresource_in_releases.yaml

- patches/categories_in_stemcells.yaml
- patches/nonempty_spec_properties_validations_in_stemcells.yaml
- patches/additional_printer_columns_in_stemcells.yaml
- patches/status_subresource_in_stemcells.yaml

- patches/categories_in_directors.yaml
- patches/nonempty_spec_properties_validations_in_directors.yaml
- patches/additional_printer_columns_in_directors.yaml

- patches/categories_in_teams.yaml
- patches/nonempty_spec_properties_validations_in_teams.yaml
- patches/additional_printer_columns_in_teams.yaml
- patches/status_subresource_in_teams.yaml

- patches/categories_in_vmextensions.yaml
- patches/additional_printer_columns_in_vmextensions.yaml
- patches/status_subresource_in_vmextensions.yaml

- patches/categories_in_azs.yaml
- patches/additional_printer_columns_in_azs.yaml
- patches/status_subresource_in_azs.yaml

- patches/categories_in_networks.yaml
- patches/nonempty_spec_properties_validations_in_networks.yaml
- patches/additional_printer_columns_in_networks.yaml
- patches/status_subresource_in_networks.yaml