# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/bosh.akgupta.ca_releases.yaml
- bases/bosh.akgupta.ca_baseimages.yaml
- bases/bosh.akgupta.ca_directors.yaml
- bases/bosh.akgupta.ca_teams.yaml
- bases/bosh.akgupta.ca_extensions.yaml
- bases/bosh.akgupta.ca_azs.yaml
- bases/bosh.akgupta.ca_networks.yaml
- bases/bosh.akgupta.ca_compilations.yaml
- bases/bosh.akgupta.ca_roles.yaml
- bases/bosh.akgupta.ca_deployments.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
- patches/categories_in_releases.yaml
- patches/nonempty_spec_properties_validations_in_releases.yaml
- patches/additional_printer_columns_in_releases.yaml
- patches/status_subresource_in_releases.yaml

- patches/categories_in_baseimages.yaml
- patches/nonempty_spec_properties_validations_in_baseimages.yaml
- patches/additional_printer_columns_in_baseimages.yaml
- patches/status_subresource_in_baseimages.yaml

- patches/categories_in_directors.yaml
- patches/nonempty_spec_properties_validations_in_directors.yaml
- patches/additional_printer_columns_in_directors.yaml

- patches/categories_in_teams.yaml
- patches/nonempty_spec_properties_validations_in_teams.yaml
- patches/additional_printer_columns_in_teams.yaml
- patches/status_subresource_in_teams.yaml

- patches/categories_in_extensions.yaml
- patches/additional_printer_columns_in_extensions.yaml
- patches/status_subresource_in_extensions.yaml

- patches/categories_in_azs.yaml
- patches/additional_printer_columns_in_azs.yaml
- patches/status_subresource_in_azs.yaml

- patches/categories_in_networks.yaml
- patches/nonempty_spec_properties_validations_in_networks.yaml
- patches/additional_printer_columns_in_networks.yaml
- patches/status_subresource_in_networks.yaml

- patches/categories_in_compilations.yaml
- patches/nonempty_spec_properties_validations_in_compilations.yaml
- patches/additional_printer_columns_in_compilations.yaml
- patches/status_subresource_in_compilations.yaml

- patches/categories_in_roles.yaml
- patches/nonempty_spec_properties_validations_in_roles.yaml

- patches/categories_in_deployments.yaml
- patches/nonempty_spec_properties_validations_in_deployments.yaml
- patches/additional_printer_columns_in_deployments.yaml
- patches/status_subresource_in_deployments.yaml