# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/bosh.akgupta.ca_releases.yaml
- bases/bosh.akgupta.ca_stemcells.yaml
- bases/bosh.akgupta.ca_directors.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_releases.yaml
#- patches/webhook_in_stemcells.yaml
#- patches/webhook_in_directors.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CAINJECTION] patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_releases.yaml
#- patches/cainjection_in_stemcells.yaml
#- patches/cainjection_in_directors.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch
- patches/categories_in_releases.yaml
- patches/nonempty_spec_properties_validations_in_releases.yaml
- patches/additional_printer_columns_in_releases.yaml
- patches/status_subresource_in_releases.yaml

- patches/categories_in_stemcells.yaml
- patches/nonempty_spec_properties_validations_in_stemcells.yaml
- patches/additional_printer_columns_in_stemcells.yaml
- patches/status_subresource_in_stemcells.yaml

- patches/scope_cluster_in_directors.yaml
- patches/categories_in_directors.yaml
- patches/nonempty_spec_properties_validations_in_directors.yaml
- patches/additional_printer_columns_in_directors.yaml

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
