apiVersion: apps/v1
kind: Deployment
metadata:
  name: boshv3-controller-manager
  labels:
    control-plane: boshv3-controller-manager
spec:
  selector:
    matchLabels:
      control-plane: boshv3-controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: boshv3-controller-manager
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
